services:
  postgres:
    image: postgres:17-alpine
    container_name: garment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: garment_user
      POSTGRES_PASSWORD: garment_password
      POSTGRES_DB: garment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
